name: Update Resume on Naukri

on:
  schedule:
    - cron: "37 6 * * *"  # Runs daily at 12:07 PM IST (6:37 AM UTC)
  workflow_dispatch:

jobs:
  update-resume:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install selenium sendgrid webdriver-manager

    - name: Install Google Chrome
      run: |
        sudo apt update
        sudo apt install -y google-chrome-stable
        google-chrome --version

    - name: Install Xvfb (Virtual Display)
      run: |
        sudo apt-get install -y x11-xserver-utils 
        Xvfb :99 -screen 0 1920x1080x24 &  
        export DISPLAY=:99.0  


    - name: Run Resume Update Script with Virtual Display
      env:
        NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &  # Start virtual display
        export DISPLAY=:99                 # Set display for GUI apps
        python Main.py                      # Run your script
